[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "triage"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "langgraph",
    "langchain",
    "langchain-openai",
    "openai",
    "python-dotenv",
    "pandas",
    "xgboost",
    "scikit-learn",
    "faiss-cpu",
    "joblib"
]

[tool.setuptools.packages.find]
where = ["src"]